version: '2.0'

services:
  web:
    image: 4xxi/caesarapp-server
    depends_on:
      - "mongodb"
    expose:
      - "9000"
    links:
      - mongodb
    entrypoint: ${WWW_DIR}/entrypoint.sh
    environment:
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_HOST: "${MONGODB_HOST}"
      MONGODB_PORT: "${MONGODB_PORT}"
      CLIENT_ORIGIN : "${CLIENT_ORIGIN}"
      SYMFONY_ENV: ${ENV}
  nginx:
    image: 4xxi/nginx
    depends_on:
      - web
    volumes:
      - ./var/logs:/var/log/nginx
      - .:${WWW_DIR}
    ports:
      - "${SERVER_HTTP_PORT}:80"
    environment:
      WWW_DIR: ${WWW_DIR}
      SYMFONY_ENV: ${ENV}
  mongodb:
    image: 4xxi/mongodb:latest
    volumes:
      - db-data:/var/lib/mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    restart: always
    environment:
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
volumes:
  db-data: {}
