version: '3.3'

services:
  web:
    image: 4xxi/php-mongo
    volumes:
      - .:${WWW_DIR}
    depends_on:
      - "mongodb"
    expose:
      - "9000"
    links:
      - mongodb
    entrypoint: ${WWW_DIR}/docker-entrypoint.sh
    environment:
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_HOST: "${MONGODB_HOST}"
      MONGODB_PORT: "${MONGODB_PORT}"
      CLIENT_ORIGIN : "${CLIENT_ORIGIN}"
   nginx:
    image: 4xxi/nginx
    depends_on:
      - web
    volumes:
      - ./var/logs:/var/log/nginx
      - .:${WWW_DIR}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
  mongodb:
    image: 4xxi/mongodb:latest
    volumes:
      - db-data:/var/lib/mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    restart: always
    environment:
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
volumes:
  db-data: {}
