version: '2.0'

services:
  appclient:
    image: 4xxi/caesarapp-web-client
    depends_on:
      - web
    volumes:
      - .env:/home/node/.env
    environment:
      NODE_ENV: ${ENV}
    ports:
      - "${CLIENT_HTTP_PORT}:4000"
