version: '3.3'

services:
  web:
    volumes:
      - ./composer.json:${WWW_DIR}/composer.json
      - ./composer.lock:${WWW_DIR}/composer.lock
      - source-data:${WWW_DIR}:nocopy
  nginx:
    volumes:
      - source-data:${WWW_DIR}

volumes:
  source-data:
    external:
      name: "caesar-source-data-unison-sync"