# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: 4xxi/php-mongo
      - image: 4xxi/nginx
      - image: 4xxi/mongodb:latest

    working_directory: $WWW_DIR

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps1-{{ .Branch }}-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-progress --no-suggest --no-interaction


      - save_cache:
          paths:
            - ./vendor
          key: deps1-{{ .Branch }}-{{ checksum "composer.json" }}

      - run:
          name: Migrations
          command: |
            bin/console doctrine:mongodb:schema:update -e prod

      # run tests!
      - run: bin/phpunit